@extends('layouts/app')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <h1>Hello, World</h1>

            <p>Why can't we just admit it? Give in now and let me in. You'll like this in. Don't pull it out. To ascend you must die. You must be crucified. Set as I am in my ways and my arrogance, burden of proof tossed upon the believers. You were my witness, my eyes, my evidence, Judith Marie, unconditional one. Mention this to me. Mention something, mention anything... and watch the weather change. Spark becomes a flame. Flame becomes a fire. Forge a blade to slay the stranger. Take whatever we desire. Where there's one you're bound to divide it right in two. My compassion is broken now. My will is eroded, and my desire stolen and it makes me feel ugly. Clutch it like a cornerstone. Otherwise it all comes down. Deaf and blind and dumb and born to follow, what you need is someone strong to use you... like me. But I'm so comfortable...Too comfortable. I'm slipping back into the gap again. Thought I could make it end. Thought I could wash the stains away. Thought I could break the circle if I slipped right into your skin. What is this but my reflection? Who am I to judge and strike you down? Why can't we not be sober? I just want to start this over.</p>

            <p>Things like.... "Fuck yourself, kill yourself, you piece of shit." Spark becomes a flame. Flame becomes a fire. Forge a blade to slay the stranger. Take whatever we desire. Me. The Chosen One? They chose me!!! And I didn't even graduate from fuckin' high school. I've come round full circle. My lamb and martyr, this will be over soon. You look so precious. I don't want to be hostile. I don't want to be dismal. I'm back down. I'm in the undertow. I'm helpless and awake in the undertow. This may hurt a little but it's something you'll get used to. My shadow's shedding skin. I've been picking my scabs again. I sold my soul to make a record, dip shit. And you bought one. Things like.... "Fuck yourself, kill yourself, you piece of shit." Don't just call me pessimist. Try and read between the lines. It was so real, like I woke up in Wonderland. Be patient. I must keep reminding myself of this. And I feel this coming over like a storm again. All you know about me is what I've sold you, dumb fuck. I sold out long before you ever heard my name.</p>

            <p>I need to watch things die from a good safe distance. Just kidding. Here in this hopeless fucking hole we call LA. The only way to fix it is to flush it all away. So what have I done to be a son to an angel? What have I done To be worthy? But I'm so comfortable...Too comfortable. I hope you're choking. I hope you choke on this. The water is rising up on me. Thought the sun would come deliver me, but the truth has come to punish me instead. Overwhelmed as one would be, placed in my position. Such a heavy burden now to be the one. Seems like I've been here before. Seems so familiar. Seems like I'm slipping into a dream within a dream. To bring the pieces back together, rediscover communication. In this holy reality, in this holy experience. Choosing to be here in this body. Silly monkeys. Give them thumbs, they make a club to beat their brother down. Lay back and let me show you another way. Black then white are all I see in my infancy. Red and yellow then came to be, reaching out to me. Lets me see. I need to watch things die from a good safe distance.</p>

            <p>Just remember I will always love you, as I claw your fucking throat away. None of them can even hold a candle up to you. Blinded by choice, these hypocrites won't see. I am not innocent. You are not innocent. No one is innocent. The water is rising up on me. Thought the sun would come deliver me, but the truth has come to punish me instead. I will find a center in you. I will chew it up and leave, I will work to elevate you just enough to bring you down. There's a shyness found in reason. Don't just call me pessimist. Try and read between the lines. They fight till they die over words, polarizing. You, my piece of mind, my all, my center, just trying to hold on one more day. And it's half as high as heaven and half as clear as reason. Some say the end is near. Some say we'll see armageddon soon. Ignorant siblings in the congregation gather around spewing sympathy. Spare me. Why did Father give these humans free will? Now they're all confused. I will find a center in you. I will chew it up and leave, I will work to elevate you just enough to bring you down. Deaf and blind and dumb and born to follow, what you need is someone strong to use you... like me.</p>

            <p>I'm back down. I'm in the undertow. I'm helpless and awake in the undertow. Leave behind this place so negative and blind and cynical, and you will come to find that we are all one mind. Eye on the TV 'cause tragedy thrills me. Whatever flavor it happens to be. You believe me, don't you? Please believe what I've just said! See the Dead ain't touring and this wasn't all in my head. To ascend you must die. You must be crucified. Why can't we just admit it? And following our will and wind we may just go where no one's been. We'll ride the spiral to the end and may just go where no one's been. Spark becomes a flame. Flame becomes a fire. Forge a blade to slay the stranger. Take whatever we desire. Defining, confining, controlling, and we're sinking deeper. What is this but my reflection? Who am I to judge and strike you down? Locked up inside you, like the calm beneath castles, is a cavern of treasures that no one has been to. You believe me, don't you? Please believe what I've just said! See the Dead ain't touring and this wasn't all in my head. How can it mean anything to me if I really don't feel anything at all? Suck me dry. All this pain is an illusion.</p>

            <p>Deaf and blind and dumb and born to follow, what you need is someone strong to use you... like me. In this holy reality, in this holy experience. Choosing to be here in this body. I hope it sucks you down. Leave behind this place so negative and blind and cynical, and you will come to find that we are all one mind. Can't remember what they said to make me out to be the hero. Locked in a place where no one goes. Repugnant is a creature who would squander the ability to lift an eye to heaven, conscious of his fleeting time here. Vicariously, I live while the whole world dies. Don't look at me like I am a monster. Frown out your one face, but with the other stare like a junkie into the TV. Can't remember what they said to make me out to be the hero. Locked up inside you, like the calm beneath castles, is a cavern of treasures that no one has been to. This body makes me feel eternal. And this little light of mine, a gift you passed on to me; I'm gonna let it shine to guide you safely on your way, Your way home. He had me crying out, "Fuck me It's gotta be the Deadhead Chemistry. The blotter got on top of me. Got me seein' E-motherfuckin'-T!" I've been struck dumb by a voice that speaks from deep beneath the cold black water.</p>
        </div>
    </div>

@endsection
